# Generated by Django 4.2.13 on 2024-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0008_whitelisttguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
