# Generated by Django 4.2.13 on 2024-05-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directionName', models.CharField(max_length=100)),
                ('directionDesc', models.CharField(max_length=200)),
                ('directionDisplay', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueName', models.CharField(max_length=100)),
                ('queueDesc', models.CharField(max_length=200)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficdb.direction')),
            ],
        ),
        migrations.CreateModel(
            name='QueueLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueLength', models.CharField(max_length=100)),
                ('queueTypeDisplay', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueTypeName', models.CharField(max_length=100)),
                ('queueTypeDisplay', models.BooleanField(default=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficdb.queue')),
                ('queueLength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficdb.queuelength')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='queueType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trafficdb.queuetype'),
        ),
    ]
