# Generated by Django 4.2.13 on 2024-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('message', models.TextField()),
                ('from_id', models.BigIntegerField()),
                ('from_is_bot', models.BooleanField()),
                ('from_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('from_username', models.CharField(blank=True, max_length=255, null=True)),
                ('from_language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
