# Generated by Django 4.2.13 on 2024-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuelength',
            options={'verbose_name_plural': 'Queue Lengths'},
        ),
        migrations.AlterModelOptions(
            name='queuestatus',
            options={'verbose_name_plural': 'Queue Statuses'},
        ),
        migrations.AlterModelOptions(
            name='queuetype',
            options={'verbose_name_plural': 'Queue Types'},
        ),
        migrations.AddField(
            model_name='queuestatus',
            name='queueColor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
