# Generated by Django 4.0.6 on 2024-06-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0002_queuelength_queuelengthvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuestatus',
            name='queueIP',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
