# Generated by Django 4.2.13 on 2024-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0002_telegramupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramupdate',
            name='update_id',
            field=models.BigIntegerField(),
        ),
    ]
