# Generated by Django 4.2.13 on 2024-05-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0002_alter_queuelength_options_alter_queuestatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuestatus',
            name='queueColor',
        ),
        migrations.AddField(
            model_name='queuelength',
            name='queueColor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
