# Generated by Django 4.2.13 on 2024-06-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0002_queuelength_queuelengthvalue'),
        ('trafficdb', '0002_queuestatus_queueip'),
    ]

    operations = [
    ]
