# Generated by Django 4.0.6 on 2024-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0003_queuestatus_queueip'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetype',
            name='queueTypeDisplayOrder',
            field=models.IntegerField(default=0),
        ),
    ]
