# Generated by Django 4.0.6 on 2024-07-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0003_alter_telegramupdate_update_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.BigIntegerField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblock_at', models.DateTimeField()),
                ('manual_unblock_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
