# Generated by Django 4.2.13 on 2024-06-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0003_merge_20240613_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuetype',
            name='queueTypeDisplayOrder',
            field=models.IntegerField(default=0),
        ),
    ]
