# Generated by Django 4.0.6 on 2024-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0004_queuetype_queuetypedisplayorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop', models.CharField(max_length=10)),
                ('service_no', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=10)),
                ('next_bus', models.JSONField()),
                ('next_bus_2', models.JSONField()),
                ('next_bus_3', models.JSONField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
