# Generated by Django 4.2.13 on 2024-07-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0004_blockedtguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtguser',
            name='from_id',
            field=models.BigIntegerField(),
        ),
    ]
