# Generated by Django 4.2.13 on 2024-07-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0005_alter_blockedtguser_from_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockedtguser',
            old_name='blocked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blockedtguser',
            old_name='manual_unblock_at',
            new_name='end_at',
        ),
        migrations.RenameField(
            model_name='blockedtguser',
            old_name='unblock_at',
            new_name='start_at',
        ),
        migrations.AddField(
            model_name='blockedtguser',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
