# Generated by Django 4.2.13 on 2024-06-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0006_busarrival_createdtime_busarrival_modifiedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop', models.CharField(max_length=10)),
                ('bus_stop_name', models.CharField(max_length=255)),
            ],
        ),
    ]
