# Generated by Django 4.2.13 on 2024-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0006_rename_blocked_at_blockedtguser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtguser',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
