# Generated by Django 5.0.7 on 2024-07-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0009_whitelistgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUpdate',
            new_name='TelegramRequest',
        ),
    ]
