# Generated by Django 5.0.7 on 2024-07-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0010_rename_telegramupdate_telegramrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramrequest',
            name='json_response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
