# Generated by Django 5.0.7 on 2024-07-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0011_telegramrequest_json_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramrequest',
            name='json_response',
            field=models.JSONField(default=""),
        ),
    ]
