# Generated by Django 5.0.7 on 2024-07-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0012_alter_telegramrequest_json_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramrequest',
            name='json_response',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
