# Generated by Django 5.0.7 on 2024-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0013_alter_telegramrequest_json_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgQueueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('command', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
