# Generated by Django 5.0.7 on 2024-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0015_remove_tgqueueupdate_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelisttguser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
