# Generated by Django 5.1 on 2024-12-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trafficdb', '0017_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='triggered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
