"""
Django settings for trafficproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
import logging
import pytz
from datetime import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rhh1+bio5api0wob7u+e#ng^va5yb%@iwa0mmg)krkx4a$adcm'
RECAPTCHA_PUBLIC_KEY = '6LeBrfEpAAAAAGjFNqMPESpOK8nlU6jp3yeS5jc_'
RECAPTCHA_PRIVATE_KEY = '6LeBrfEpAAAAAIt70mRTd11iI2b4VpXsXwIVMYLB'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['mygowhere.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    'trafficdb.apps.TrafficdbConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'trafficdb.middleware.BlockNonLocalMiddleware',
]

ROOT_URLCONF = 'trafficproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trafficproject.wsgi.application'

#Logging
#Logging of application

class AsiaSingaporeFormatter(logging.Formatter):
    def converter(self, timestamp):
        dt = datetime.fromtimestamp(timestamp)  # Corrected usage
        tz = pytz.timezone('Asia/Singapore')
        return dt.astimezone(tz)

    def formatTime(self, record, datefmt=None):
        dt = self.converter(record.created)
        if datefmt:
            return dt.strftime(datefmt)
        else:
            return dt.isoformat()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'asia_singapore': {
            '()': AsiaSingaporeFormatter,
            'format': '%(asctime)s %(levelname)s %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/home/mygowhere/logs/info.log',
            'formatter': 'asia_singapore',
            'when': 'D',  # Rotate daily
            'interval': 1,  # Every 1 day
            'backupCount': 7,  # Keep 3 days worth of logs
        },
        'trafficdb_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/home/mygowhere/logs/app.log',
            'formatter': 'asia_singapore',
            'when': 'D',  # Rotate daily
            'interval': 1,  # Every 1 day
            'backupCount': 7,  # Keep 3 days worth of logs
        },
        'trafficdb_middleware_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/home/mygowhere/logs/middleware.log',
            'formatter': 'asia_singapore',
            'when': 'D',  # Rotate daily
            'interval': 1,  # Every 1 day
            'backupCount': 7,  # Keep 3 days worth of logs
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'trafficdb': {  # Replace 'myapp' with your application's name
            'handlers': ['trafficdb_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'trafficdb_middleware': {  # Replace 'myapp' with your application's name
            'handlers': ['trafficdb_middleware_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mygowhere$default',
        'USER': 'mygowhere',
        'PASSWORD': 'kuku8888my',
        'HOST': 'mygowhere.mysql.pythonanywhere-services.com',  # Usually 'localhost' or an IP address
        'PORT': '3306',  # Default MySQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = '/home/mygowhere/trafficproject/static'
RECAPTCHA_REQUIRED_SCORE = 0.85
